// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/_locales/hu/messages.json"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/images/blocks/close.png"
    | "/images/blocks/down.png"
    | "/images/blocks/left.png"
    | "/images/blocks/minimize.png"
    | "/images/blocks/right.png"
    | "/images/blocks/up.png"
    | "/images/cleditor/buttons.gif"
    | "/images/cleditor/toolbar.gif"
    | "/images/content/background.png"
    | "/images/content/comments_for_me_indicator.png"
    | "/images/content/ext_hsep_bg.png"
    | "/images/content/info.png"
    | "/images/content/lampOff.png"
    | "/images/content/lampOn.png"
    | "/images/content/mark-read.png"
    | "/images/content/mark-read_done.png"
    | "/images/content/mark-read_waiting.png"
    | "/images/content/overlay_close.png"
    | "/images/content/refresh.png"
    | "/images/content/refresh_done.png"
    | "/images/content/refresh_waiting.png"
    | "/images/content/search.png"
    | "/images/content/star.png"
    | "/images/content/warning.png"
    | "/images/content/warning2.png"
    | "/images/settings/button.png"
    | "/images/settings/icon.png"
    | "/images/settings/icons.png"
    | "/images/settings/selected.png"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
